"use client";

import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useState,
  type ReactNode,
} from "react";

type Language = "en" | "fr" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const STORAGE_KEY = "medlearn-lang";

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.majors": "Majors",
    "nav.modules": "Modules",
    "nav.resources": "Resources",
    "nav.quizzes": "Quizzes",
    "nav.homework": "Homework",
    "nav.admin": "Admin",
    "nav.login": "Login",
    "nav.signup": "Sign Up",
    "nav.logout": "Logout",
    "home.title": "MEDlearn",
    "home.subtitle": "Open-access educational platform for medical students",
    "home.explore": "Explore Majors",
    "home.featured": "Academic Programs",
    "majors.title": "Academic Majors",
    "majors.modules": "modules",
    "modules.title": "Modules",
    "modules.resources": "resources",
    "resources.title": "Resources",
    "resources.search": "Search resources...",
    "resources.filter_type": "Filter by type",
    "resources.all": "All",
    "resources.file": "File",
    "resources.link": "Link",
    "resources.youtube": "YouTube",
    "resources.text": "Text",
    "resources.empty": "No resources found",
    "resources.download": "Download",
    "resources.open_link": "Open Link",
    "admin.title": "Admin Dashboard",
    "admin.majors": "Majors",
    "admin.modules": "Modules",
    "admin.resources": "Resources",
    "admin.add": "Add",
    "admin.edit": "Edit",
    "admin.delete": "Delete",
    "admin.save": "Save",
    "admin.cancel": "Cancel",
    "admin.name": "Name",
    "admin.order": "Order",
    "admin.major": "Major",
    "admin.module": "Module",
    "admin.type": "Type",
    "admin.title_field": "Title",
    "admin.description": "Description",
    "admin.published": "Published",
    "admin.language": "Language",
    "admin.content": "Content",
    "admin.file": "File",
    "admin.link": "Link URL",
    "admin.youtube_id": "YouTube Video ID",
    "login.title": "Sign In",
    "login.email": "Email",
    "login.password": "Password",
    "login.submit": "Sign In",
    "login.error": "Invalid credentials",
    "empty.majors":
      "No academic majors are listed yet. Check back soon, or contact your course administrator.",
    "empty.modules":
      "This major does not list any modules yet. Content may still be in preparation.",
    "empty.resources":
      "No learning resources are published for this module yet.",
    "empty.search_results":
      "No resources match your search or filters. Try different keywords or clear the filters.",
    "empty.admin.majors": "No majors yet. Add a major to start structuring the catalog.",
    "empty.admin.modules": "No modules yet. Create a module under a major to organize resources.",
    "empty.admin.resources":
      "No resources yet. Add files, links, videos, or text blocks for students.",
    "validation.major_name": "Please enter a major name.",
    "validation.module_name": "Please enter a module name.",
    "validation.resource_title": "Please enter a resource title.",
    "validation.major_module": "Choose a major and a module that belongs to it.",
    "validation.language": "Use a short language code such as en, fr, or ar.",
    "validation.file_pick": "Choose a file to upload.",
    "validation.file_url": "A file URL is required for this resource.",
    "validation.url": "Enter a valid URL starting with http:// or https://.",
    "validation.youtube": "Enter a valid YouTube video ID (letters, numbers, dash, underscore).",
    "validation.text": "Enter the text content for this resource.",
    "validation.resource_type": "Unsupported resource type.",
    "admin.subtitle":
      "Manage majors, modules, and resources. Signed-in users can edit catalog content.",
    "admin.helper.order": "Lower numbers appear first in public listings.",
    "admin.helper.reorder": "Move up or down to adjust display order.",
    "admin.helper.select_major": "Select a major first, then add modules and resources.",
    "admin.file.choose": "Choose file",
    "admin.file.hint": "No file selected yet. Files are stored in Supabase Storage (resources bucket).",
    "admin.file.selected": "Selected",
    "admin.file.replace": "Replace file",
    "admin.file.uploading": "Uploading file…",
    "admin.file.success": "File uploaded successfully.",
    "admin.file.fail": "File upload failed. Please try again.",
    "admin.file.current": "Current file URL",
    "admin.delete.prompt": "You are about to delete:",
    "admin.delete.cannot_undo": "This cannot be undone.",
    "admin.delete.confirm_btn": "Confirm delete",
    "admin.loading": "Loading catalog…",
    "admin.nav.section": "Management",
    "admin.nav.dashboard": "Dashboard",
    "admin.nav.catalog": "Majors & Modules",
    "admin.nav.resources": "Resources",
    "admin.nav.questions": "Question Bank",
    "admin.nav.quizzes": "Quiz Builder",
    "admin.nav.homework": "Homework",
    "admin.quicklinks": "Quick Links",
    "admin.questions.count": "questions",
    "admin.questions.new": "New Question",
    "admin.questions.edit": "Edit Question",
    "admin.questions.empty": "No questions yet. Create one to build your question bank.",
    "admin.questions.type": "Question Type",
    "admin.questions.statement": "Statement",
    "admin.questions.options": "Answer Options",
    "admin.questions.correct": "Correct Answer",
    "admin.questions.add_option": "Add Option",
    "admin.questions.difficulty": "Difficulty",
    "admin.questions.explanation": "Explanation",
    "admin.questions.tags": "Tags",
    "admin.questions.tags_hint": "Press Enter or comma to add",
    "admin.questions.scq_hint": "Click a letter to mark the single correct answer",
    "admin.questions.mcq_hint": "Click letters to mark all correct answers",
    "quiz.untitled": "Untitled Quiz",
    "quiz.exam_mode": "Exam",
    "quiz.practice_mode": "Practice",
    "quiz.start_cta": "Click to start →",
    "quiz.no_questions": "This quiz has no questions yet.",
    "quiz.back": "Back to Quizzes",
    "quiz.retry": "Try Again",
    "quiz.results": "Quiz Results",
    "quiz.correct": "correct",
    "quiz.pass": "Passed",
    "quiz.fail": "Failed",
    "quiz.required": "required",
    "quiz.review": "Review",
    "quiz.explanation": "Explanation",
    "quiz.question": "Question",
    "quiz.prev": "Previous",
    "quiz.next": "Next",
    "quiz.submit": "Submit Quiz",
    "quiz.grading": "Grading…",
    "quiz.see_results": "See Results",
    "quiz.true": "True",
    "quiz.false": "False",
    "homework.untitled": "Untitled Homework",
    "homework.due": "Due",
    "homework.attachments": "Attachments",
    "homework.submit_cta": "Submit Assignment",
    "homework.submit": "Submit",
    "homework.submitting": "Submitting…",
    "homework.submit_success": "Your submission was received successfully!",
    "homework.submit_error": "Submission failed. Please try again.",
    "homework.your_name": "Your Name",
    "homework.your_email": "Email (optional)",
    "homework.text_answer": "Text Answer",
    "homework.text_placeholder": "Write your answer here…",
    "homework.link_submission": "Link Submission",
    "homework.validation.name": "Please enter your name.",
    "homework.validation.content": "Please add an answer, file, or link.",
    "empty.quizzes": "No quizzes published for this module yet.",
    "empty.homework": "No homework published for this module yet.",
    "footer.rights": "© 2026 MEDlearn. All rights reserved.",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.majors": "Filières",
    "nav.modules": "Modules",
    "nav.resources": "Ressources",
    "nav.quizzes": "Quiz",
    "nav.homework": "Devoirs",
    "nav.admin": "Admin",
    "nav.login": "Connexion",
    "nav.signup": "S'inscrire",
    "nav.logout": "Déconnexion",
    "home.title": "MEDlearn",
    "home.subtitle": "Plateforme éducative en libre accès pour les étudiants en médecine",
    "home.explore": "Explorer les filières",
    "home.featured": "Programmes académiques",
    "majors.title": "Filières académiques",
    "majors.modules": "modules",
    "modules.title": "Modules",
    "modules.resources": "ressources",
    "resources.title": "Ressources",
    "resources.search": "Rechercher des ressources...",
    "resources.filter_type": "Filtrer par type",
    "resources.all": "Tout",
    "resources.file": "Fichier",
    "resources.link": "Lien",
    "resources.youtube": "YouTube",
    "resources.text": "Texte",
    "resources.empty": "Aucune ressource trouvée",
    "resources.download": "Télécharger",
    "resources.open_link": "Ouvrir le lien",
    "admin.title": "Tableau de bord",
    "admin.majors": "Filières",
    "admin.modules": "Modules",
    "admin.resources": "Ressources",
    "admin.add": "Ajouter",
    "admin.edit": "Modifier",
    "admin.delete": "Supprimer",
    "admin.save": "Enregistrer",
    "admin.cancel": "Annuler",
    "admin.name": "Nom",
    "admin.order": "Ordre",
    "admin.major": "Filière",
    "admin.module": "Module",
    "admin.type": "Type",
    "admin.title_field": "Titre",
    "admin.description": "Description",
    "admin.published": "Publié",
    "admin.language": "Langue",
    "admin.content": "Contenu",
    "admin.file": "Fichier",
    "admin.link": "URL du lien",
    "admin.youtube_id": "ID vidéo YouTube",
    "login.title": "Connexion",
    "login.email": "Email",
    "login.password": "Mot de passe",
    "login.submit": "Se connecter",
    "login.error": "Identifiants invalides",
    "empty.majors":
      "Aucune filière académique n’est encore publiée. Revenez plus tard ou contactez l’administration.",
    "empty.modules":
      "Cette filière ne comporte pas encore de modules. Le contenu est peut‑être en préparation.",
    "empty.resources":
      "Aucune ressource d’apprentissage n’est publiée pour ce module.",
    "empty.search_results":
      "Aucune ressource ne correspond à votre recherche ou à vos filtres.",
    "empty.admin.majors": "Aucune filière. Ajoutez une filière pour structurer le catalogue.",
    "empty.admin.modules": "Aucun module. Créez un module rattaché à une filière.",
    "empty.admin.resources":
      "Aucune ressource. Ajoutez des fichiers, liens, vidéos ou textes pour les étudiants.",
    "validation.major_name": "Indiquez un nom de filière.",
    "validation.module_name": "Indiquez un nom de module.",
    "validation.resource_title": "Indiquez un titre de ressource.",
    "validation.major_module": "Choisissez une filière et un module qui lui appartient.",
    "validation.language": "Utilisez un code court : en, fr ou ar.",
    "validation.file_pick": "Choisissez un fichier à téléverser.",
    "validation.file_url": "Une URL de fichier est requise pour cette ressource.",
    "validation.url": "Saisissez une URL valide commençant par http:// ou https://.",
    "validation.youtube": "Saisissez un ID vidéo YouTube valide.",
    "validation.text": "Saisissez le contenu texte de la ressource.",
    "validation.resource_type": "Type de ressource non pris en charge.",
    "admin.subtitle":
      "Gérez filières, modules et ressources. Les utilisateurs connectés peuvent modifier le catalogue.",
    "admin.helper.order": "Les nombres plus petits apparaissent en premier sur le site public.",
    "admin.helper.reorder": "Déplacez vers le haut ou le bas pour modifier l’ordre d’affichage.",
    "admin.helper.select_major": "Choisissez d’abord une filière, puis ajoutez modules et ressources.",
    "admin.file.choose": "Choisir un fichier",
    "admin.file.hint":
      "Aucun fichier sélectionné. Les fichiers sont enregistrés dans le bucket Supabase « resources ».",
    "admin.file.selected": "Fichier sélectionné",
    "admin.file.replace": "Remplacer le fichier",
    "admin.file.uploading": "Téléversement…",
    "admin.file.success": "Fichier téléversé avec succès.",
    "admin.file.fail": "Échec du téléversement. Réessayez.",
    "admin.file.current": "URL du fichier actuel",
    "admin.delete.prompt": "Vous allez supprimer :",
    "admin.delete.cannot_undo": "Cette action est irréversible.",
    "admin.delete.confirm_btn": "Confirmer la suppression",
    "admin.loading": "Chargement du catalogue…",
    "admin.nav.section": "Gestion",
    "admin.nav.dashboard": "Tableau de bord",
    "admin.nav.catalog": "Filières & Modules",
    "admin.nav.resources": "Ressources",
    "admin.nav.questions": "Banque de questions",
    "admin.nav.quizzes": "Créateur de quiz",
    "admin.nav.homework": "Devoirs",
    "admin.quicklinks": "Liens rapides",
    "admin.questions.count": "questions",
    "admin.questions.new": "Nouvelle question",
    "admin.questions.edit": "Modifier la question",
    "admin.questions.empty": "Aucune question. Créez-en une pour alimenter la banque.",
    "admin.questions.type": "Type de question",
    "admin.questions.statement": "Énoncé",
    "admin.questions.options": "Options de réponse",
    "admin.questions.correct": "Bonne réponse",
    "admin.questions.add_option": "Ajouter une option",
    "admin.questions.difficulty": "Difficulté",
    "admin.questions.explanation": "Explication",
    "admin.questions.tags": "Étiquettes",
    "admin.questions.tags_hint": "Appuyez sur Entrée ou virgule pour ajouter",
    "admin.questions.scq_hint": "Cliquez sur une lettre pour marquer la bonne réponse",
    "admin.questions.mcq_hint": "Cliquez sur les lettres pour marquer toutes les bonnes réponses",
    "quiz.untitled": "Quiz sans titre",
    "quiz.exam_mode": "Examen",
    "quiz.practice_mode": "Entraînement",
    "quiz.start_cta": "Cliquer pour commencer →",
    "quiz.no_questions": "Ce quiz n'a pas encore de questions.",
    "quiz.back": "Retour aux quiz",
    "quiz.retry": "Réessayer",
    "quiz.results": "Résultats",
    "quiz.correct": "correct(s)",
    "quiz.pass": "Réussi",
    "quiz.fail": "Échoué",
    "quiz.required": "requis",
    "quiz.review": "Révision",
    "quiz.explanation": "Explication",
    "quiz.question": "Question",
    "quiz.prev": "Précédent",
    "quiz.next": "Suivant",
    "quiz.submit": "Soumettre",
    "quiz.grading": "Correction…",
    "quiz.see_results": "Voir les résultats",
    "quiz.true": "Vrai",
    "quiz.false": "Faux",
    "homework.untitled": "Devoir sans titre",
    "homework.due": "Échéance",
    "homework.attachments": "Pièces jointes",
    "homework.submit_cta": "Soumettre le devoir",
    "homework.submit": "Soumettre",
    "homework.submitting": "Envoi…",
    "homework.submit_success": "Votre devoir a été soumis avec succès !",
    "homework.submit_error": "Échec de la soumission. Réessayez.",
    "homework.your_name": "Votre nom",
    "homework.your_email": "Email (facultatif)",
    "homework.text_answer": "Réponse écrite",
    "homework.text_placeholder": "Rédigez votre réponse ici…",
    "homework.link_submission": "Lien de soumission",
    "homework.validation.name": "Veuillez entrer votre nom.",
    "homework.validation.content": "Ajoutez une réponse, un fichier ou un lien.",
    "empty.quizzes": "Aucun quiz publié pour ce module.",
    "empty.homework": "Aucun devoir publié pour ce module.",
    "footer.rights": "© 2026 MEDlearn. Tous droits réservés.",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.majors": "التخصصات",
    "nav.modules": "الوحدات",
    "nav.resources": "الموارد",
    "nav.quizzes": "الاختبارات",
    "nav.homework": "الواجبات",
    "nav.admin": "الإدارة",
    "nav.login": "تسجيل الدخول",
    "nav.signup": "إنشاء حساب",
    "nav.logout": "تسجيل الخروج",
    "home.title": "MEDlearn",
    "home.subtitle": "منصة تعليمية مفتوحة لطلاب الطب",
    "home.explore": "استكشاف التخصصات",
    "home.featured": "البرامج الأكاديمية",
    "majors.title": "التخصصات الأكاديمية",
    "majors.modules": "وحدات",
    "modules.title": "الوحدات",
    "modules.resources": "موارد",
    "resources.title": "الموارد",
    "resources.search": "البحث في الموارد...",
    "resources.filter_type": "تصفية حسب النوع",
    "resources.all": "الكل",
    "resources.file": "ملف",
    "resources.link": "رابط",
    "resources.youtube": "يوتيوب",
    "resources.text": "نص",
    "resources.empty": "لا توجد موارد",
    "resources.download": "تحميل",
    "resources.open_link": "فتح الرابط",
    "admin.title": "لوحة الإدارة",
    "admin.majors": "التخصصات",
    "admin.modules": "الوحدات",
    "admin.resources": "الموارد",
    "admin.add": "إضافة",
    "admin.edit": "تعديل",
    "admin.delete": "حذف",
    "admin.save": "حفظ",
    "admin.cancel": "إلغاء",
    "admin.name": "الاسم",
    "admin.order": "الترتيب",
    "admin.major": "التخصص",
    "admin.module": "الوحدة",
    "admin.type": "النوع",
    "admin.title_field": "العنوان",
    "admin.description": "الوصف",
    "admin.published": "منشور",
    "admin.language": "اللغة",
    "admin.content": "المحتوى",
    "admin.file": "ملف",
    "admin.link": "رابط URL",
    "admin.youtube_id": "معرف فيديو يوتيوب",
    "login.title": "تسجيل الدخول",
    "login.email": "البريد الإلكتروني",
    "login.password": "كلمة المرور",
    "login.submit": "تسجيل الدخول",
    "login.error": "بيانات غير صحيحة",
    "empty.majors": "لا توجد تخصصات أكاديمية منشورة بعد. يمكنك العودة لاحقًا أو التواصل مع الإدارة.",
    "empty.modules": "لا توجد وحدات لهذا التخصص بعد. قد يكون المحتوى قيد الإعداد.",
    "empty.resources": "لا توجد موارد تعليمية منشورة لهذه الوحدة بعد.",
    "empty.search_results": "لا توجد موارد تطابق البحث أو التصفية. جرّب كلمات أخرى.",
    "empty.admin.majors": "لا توجد تخصصات بعد. أضِف تخصصًا لبدء تنظيم المحتوى.",
    "empty.admin.modules": "لا توجد وحدات بعد. أنشئ وحدة تحت تخصص لتنظيم الموارد.",
    "empty.admin.resources": "لا توجد موارد بعد. أضف ملفات أو روابط أو فيديو أو نصوص للطلاب.",
    "validation.major_name": "يرجى إدخال اسم التخصص.",
    "validation.module_name": "يرجى إدخال اسم الوحدة.",
    "validation.resource_title": "يرجى إدخال عنوان المورد.",
    "validation.major_module": "اختر تخصصًا ووحدة تتبع له.",
    "validation.language": "استخدم رمز لغة قصير مثل en أو fr أو ar.",
    "validation.file_pick": "اختر ملفًا لرفعه.",
    "validation.file_url": "مطلوب رابط الملف لهذا المورد.",
    "validation.url": "أدخل رابطًا صالحًا يبدأ بـ http:// أو https://.",
    "validation.youtube": "أدخل معرف فيديو يوتيوب صالحًا.",
    "validation.text": "أدخل محتوى النص للمورد.",
    "validation.resource_type": "نوع المورد غير مدعوم.",
    "admin.subtitle": "إدارة التخصصات والوحدات والموارد. يمكن للمستخدمين المسجلين تعديل المحتوى.",
    "admin.helper.order": "الأرقام الأصغر تظهر أولًا في الموقع العام.",
    "admin.helper.reorder": "انقل لأعلى أو لأسفل لضبط ترتيب العرض.",
    "admin.helper.select_major": "اختر التخصص أولًا، ثم أضف الوحدات والموارد.",
    "admin.file.choose": "اختر ملفًا",
    "admin.file.hint": "لم يُحدد ملف بعد. تُخزَّن الملفات في تخزين Supabase (حاوية resources).",
    "admin.file.selected": "الملف المحدد",
    "admin.file.replace": "استبدال الملف",
    "admin.file.uploading": "جاري رفع الملف…",
    "admin.file.success": "تم رفع الملف بنجاح.",
    "admin.file.fail": "فشل رفع الملف. حاول مرة أخرى.",
    "admin.file.current": "رابط الملف الحالي",
    "admin.delete.prompt": "أنت على وشك حذف:",
    "admin.delete.cannot_undo": "لا يمكن التراجع عن هذا الإجراء.",
    "admin.delete.confirm_btn": "تأكيد الحذف",
    "admin.loading": "جاري تحميل المحتوى…",
    "admin.nav.section": "الإدارة",
    "admin.nav.dashboard": "لوحة التحكم",
    "admin.nav.catalog": "التخصصات والوحدات",
    "admin.nav.resources": "الموارد",
    "admin.nav.questions": "بنك الأسئلة",
    "admin.nav.quizzes": "منشئ الاختبارات",
    "admin.nav.homework": "الواجبات",
    "admin.quicklinks": "روابط سريعة",
    "admin.questions.count": "أسئلة",
    "admin.questions.new": "سؤال جديد",
    "admin.questions.edit": "تعديل السؤال",
    "admin.questions.empty": "لا أسئلة بعد. أنشئ سؤالًا لبدء بنك الأسئلة.",
    "admin.questions.type": "نوع السؤال",
    "admin.questions.statement": "نص السؤال",
    "admin.questions.options": "خيارات الإجابة",
    "admin.questions.correct": "الإجابة الصحيحة",
    "admin.questions.add_option": "إضافة خيار",
    "admin.questions.difficulty": "الصعوبة",
    "admin.questions.explanation": "التفسير",
    "admin.questions.tags": "الوسوم",
    "admin.questions.tags_hint": "اضغط Enter أو فاصلة للإضافة",
    "admin.questions.scq_hint": "انقر على حرف لتحديد الإجابة الصحيحة",
    "admin.questions.mcq_hint": "انقر على الحروف لتحديد جميع الإجابات الصحيحة",
    "quiz.untitled": "اختبار بلا عنوان",
    "quiz.exam_mode": "امتحان",
    "quiz.practice_mode": "تدريب",
    "quiz.start_cta": "انقر للبدء →",
    "quiz.no_questions": "لا توجد أسئلة في هذا الاختبار بعد.",
    "quiz.back": "العودة إلى الاختبارات",
    "quiz.retry": "إعادة المحاولة",
    "quiz.results": "نتائج الاختبار",
    "quiz.correct": "صحيح",
    "quiz.pass": "ناجح",
    "quiz.fail": "راسب",
    "quiz.required": "مطلوب",
    "quiz.review": "مراجعة",
    "quiz.explanation": "التفسير",
    "quiz.question": "سؤال",
    "quiz.prev": "السابق",
    "quiz.next": "التالي",
    "quiz.submit": "إرسال الاختبار",
    "quiz.grading": "جاري التصحيح…",
    "quiz.see_results": "عرض النتائج",
    "quiz.true": "صحيح",
    "quiz.false": "خطأ",
    "homework.untitled": "واجب بلا عنوان",
    "homework.due": "تاريخ التسليم",
    "homework.attachments": "المرفقات",
    "homework.submit_cta": "تسليم الواجب",
    "homework.submit": "تسليم",
    "homework.submitting": "جارٍ الإرسال…",
    "homework.submit_success": "تم استلام إجابتك بنجاح!",
    "homework.submit_error": "فشل التسليم. حاول مرة أخرى.",
    "homework.your_name": "اسمك",
    "homework.your_email": "البريد الإلكتروني (اختياري)",
    "homework.text_answer": "الإجابة النصية",
    "homework.text_placeholder": "اكتب إجابتك هنا…",
    "homework.link_submission": "رابط التسليم",
    "homework.validation.name": "يرجى إدخال اسمك.",
    "homework.validation.content": "أضف إجابة أو ملفًا أو رابطًا.",
    "empty.quizzes": "لا توجد اختبارات منشورة لهذه الوحدة بعد.",
    "empty.homework": "لا توجد واجبات منشورة لهذه الوحدة بعد.",
    "footer.rights": "© 2026 MEDlearn. جميع الحقوق محفوظة.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

function readStoredLanguage(): Language | null {
  if (typeof window === "undefined") return null;
  const saved = window.localStorage.getItem(STORAGE_KEY);
  if (saved === "en" || saved === "fr" || saved === "ar") return saved;
  return null;
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  const [ready, setReady] = useState(false);

  useEffect(() => {
    const stored = readStoredLanguage();
    // eslint-disable-next-line react-hooks/set-state-in-effect
    if (stored) setLanguageState(stored);
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setReady(true);
  }, []);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      window.localStorage.setItem(STORAGE_KEY, lang);
    }
  }, []);

  const dir = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    if (!ready) return;
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language, dir, ready]);

  const t = useCallback(
    (key: string) => translations[language][key] ?? key,
    [language],
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
