"use client";

import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useState,
  type ReactNode,
} from "react";

type Language = "en" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const STORAGE_KEY = "medlearn-lang";

const translations: Record<Language, Record<string, string>> = {
  en: {
    "payment.pending.title": "Account Pending Activation",
    "payment.pending.subtitle": "Your account is awaiting approval from an administrator.",
    "payment.pending.step1": "An administrator reviews your account",
    "payment.pending.step2": "Once approved, you will gain access to all MEDlearn content",
    "payment.pending.step3": "Refresh this page or sign out and back in to see the change",
    "payment.activated": "Account Active",
    "payment.activated_msg": "Your account is active. You have full access to MEDlearn content.",
    "nav.home": "Home",
    "nav.majors": "Majors",
    "nav.modules": "Modules",
    "nav.resources": "Resources",
    "nav.quizzes": "Quizzes",
    "nav.admin": "Admin",
    "nav.login": "Login",
    "nav.signup": "Sign Up",
    "nav.logout": "Logout",
    "home.title": "MEDlearn",
    "home.subtitle": "Open-access educational platform for medical students",
    "home.badge": "Open Access · Free Forever",
    "home.learnmore": "Browse Modules",
    "home.stat.modules": "Modules",
    "home.stat.resources": "Resources",
    "home.programs_label": "Academic Programs",
    "home.viewall": "View all",
    "home.explore_major": "Explore major",
    "home.community": "Built for the medical student community",
    "home.cta_title": "Start Learning Today",
    "home.cta_sub": "No account needed. Just open and learn.",
    "home.explore": "Explore Majors",
    "home.featured": "Academic Programs",
    "home.empty_title": "No Majors Yet",
    "home.empty_desc": "Academic programs are being prepared. Check back soon or get started by exploring available modules.",
    "home.empty_cta": "Explore Modules",
    "majors.title": "Academic Majors",
    "majors.modules": "modules",
    "majors.available": "{count} major available",
    "majors.available_plural": "{count} majors available",
    "majors.search": "Search majors...",
    "majors.empty_title": "No Majors Found",
    "majors.empty_desc": "No academic majors are listed yet. Create one to get started.",
    "majors.empty_search": "No majors match your search. Try different keywords.",
    "majors.empty_cta": "Create Major",
    "modules.title": "Modules",
    "modules.resources": "resources",
    "modules.single": "module",
    "modules.search": "Search modules...",
    "modules.open": "Open module",
    "header.light_mode": "Light Mode",
    "header.dark_mode": "Dark Mode",
    "header.language": "Language",
    "header.toggle_theme": "Switch to {mode} mode",
    "header.toggle_menu": "Toggle navigation menu",
    "resources.title": "Resources",
    "resources.search": "Search resources...",
    "resources.filter_type": "Filter by type",
    "resources.all": "All",
    "resources.file": "File",
    "resources.link": "Link",
    "resources.youtube": "YouTube",
    "resources.text": "Text",
    "resources.empty": "No resources found",
    "resources.download": "Download",
    "resources.open_link": "Open Link",
    "admin.title": "Admin Dashboard",
    "admin.majors": "Majors",
    "admin.modules": "Modules",
    "admin.resources": "Resources",
    "admin.add": "Add",
    "admin.edit": "Edit",
    "admin.delete": "Delete",
    "admin.save": "Save",
    "admin.cancel": "Cancel",
    "admin.name": "Name",
    "admin.order": "Order",
    "admin.major": "Major",
    "admin.module": "Module",
    "admin.type": "Type",
    "admin.title_field": "Title",
    "admin.description": "Description",
    "admin.published": "Published",
    "admin.language": "Language",
    "admin.content": "Content",
    "admin.file": "File",
    "admin.link": "Link URL",
    "admin.youtube_id": "YouTube Video / Playlist (ID or Link)",
    "login.title": "Sign In",
    "login.email": "Email",
    "login.password": "Password",
    "login.submit": "Sign In",
    "login.error": "Invalid credentials",
    "empty.majors":
      "No academic majors are listed yet. Check back soon, or contact your course administrator.",
    "empty.modules":
      "This major does not list any modules yet. Content may still be in preparation.",
    "empty.resources":
      "No learning resources are published for this module yet.",
    "empty.search_results":
      "No resources match your search or filters. Try different keywords or clear the filters.",
    "empty.admin.majors": "No majors yet. Add a major to start structuring the catalog.",
    "empty.admin.modules": "No modules yet. Create a module under a major to organize resources.",
    "empty.admin.resources":
      "No resources yet. Add files, links, videos, or text blocks for students.",
    "validation.major_name": "Please enter a major name.",
    "validation.module_name": "Please enter a module name.",
    "validation.resource_title": "Please enter a resource title.",
    "validation.major_module": "Choose a major and a module that belongs to it.",
    "validation.language": "Use a short language code such as en or fr.",
    "validation.file_pick": "Choose a file to upload.",
    "validation.file_url": "A file URL is required for this resource.",
    "validation.url": "Enter a valid URL starting with http:// or https://.",
    "validation.youtube": "Enter a valid YouTube video/playlist ID or link.",
    "validation.text": "Enter the text content for this resource.",
    "validation.resource_type": "Unsupported resource type.",
    "admin.subtitle":
      "Manage majors, modules, and resources. Signed-in users can edit catalog content.",
    "admin.helper.order": "Lower numbers appear first in public listings.",
    "admin.helper.reorder": "Move up or down to adjust display order.",
    "admin.helper.select_major": "Select a major first, then add modules and resources.",
    "admin.file.choose": "Choose file",
    "admin.file.hint": "No file selected yet. Files are stored in Supabase Storage (resources bucket).",
    "admin.file.selected": "Selected",
    "admin.file.replace": "Replace file",
    "admin.file.uploading": "Uploading file…",
    "admin.file.success": "File uploaded successfully.",
    "admin.file.fail": "File upload failed. Please try again.",
    "admin.file.current": "Current file URL",
    "admin.delete.prompt": "You are about to delete:",
    "admin.delete.cannot_undo": "This cannot be undone.",
    "admin.delete.confirm_btn": "Confirm delete",
    "admin.loading": "Loading catalog…",
    "admin.nav.section": "Management",
    "admin.nav.dashboard": "Dashboard",
    "admin.nav.catalog": "Majors & Modules",
    "admin.nav.resources": "Resources",
    "admin.nav.questions": "Question Bank",
    "admin.nav.quizzes": "Quiz Builder",
    "admin.nav.users": "Users",
    "admin.branding": "MEDlearn Admin",
    "admin.quicklinks": "Quick Links",
    "admin.quiz.title": "Title",
    "admin.quiz.title_placeholder": "e.g. Cardiovascular Quiz",
    "admin.description_placeholder": "Optional description of the quiz...",
    "admin.quiz.select_major_hint": "Select a major first",
    "admin.quiz.available": "Available Questions",
    "admin.quiz.search_questions": "Search questions...",
    "admin.quiz.no_questions_match": "No published questions match the selected major/module.",
    "admin.quiz.selected": "Selected Questions",
    "admin.quiz.no_questions_selected": "No questions added yet.",
    "admin.quiz.empty": "No quizzes yet.",
    "admin.quiz.create": "Create Quiz",
    "admin.quiz.draft": "Draft",
    "admin.questions.count": "questions",
    "admin.questions.new": "New Question",
    "admin.questions.edit": "Edit Question",
    "admin.questions.empty": "No questions yet. Create one to build your question bank.",
    "admin.questions.type": "Question Type",
    "admin.questions.statement": "Statement",
    "admin.questions.statement_placeholder": "Write the question statement...",
    "admin.questions.explanation_placeholder": "Explain the correct answer...",
    "admin.questions.options": "Answer Options",
    "admin.questions.correct": "Correct Answer",
    "admin.questions.add_option": "Add Option",
    "admin.questions.difficulty": "Difficulty",
    "admin.questions.explanation": "Explanation",
    "admin.questions.tags": "Tags",
    "admin.questions.tags_hint": "Press Enter or comma to add",
    "admin.questions.scq_hint": "Click a letter to mark the single correct answer",
    "admin.questions.mcq_hint": "Click letters to mark all correct answers",
    "admin.questions.mark_correct": "Mark as correct",
    "admin.questions.difficulty_none": "None",
    "admin.questions.all_majors": "All Majors",
    "admin.questions.all_modules": "All Modules",
    "admin.questions.all_types": "All Types",
    "admin.questions.search": "Search statement…",
    "quiz.untitled": "Untitled Quiz",
    "quiz.exam_mode": "Exam",
    "quiz.practice_mode": "Practice",
    "quiz.start_cta": "Click to start →",
    "quiz.no_questions": "This quiz has no questions yet.",
    "quiz.back": "Back to Quizzes",
    "quiz.retry": "Try Again",
    "quiz.results": "Quiz Results",
    "quiz.correct": "correct",
    "quiz.pass": "Passed",
    "quiz.fail": "Failed",
    "quiz.required": "required",
    "quiz.review": "Review",
    "quiz.explanation": "Explanation",
    "quiz.question": "Question",
    "quiz.prev": "Previous",
    "quiz.next": "Next",
    "quiz.submit": "Submit Quiz",
    "quiz.grading": "Grading…",
    "quiz.see_results": "See Results",
    "quiz.true": "True",
    "quiz.false": "False",
    "empty.quizzes": "No quizzes published for this module yet.",
    "quiz.plural": "Quizzes",
    "quiz.new": "New Quiz",
    "quiz.edit": "Edit Quiz",
    "quiz.rules": "Quiz Rules",
    "quiz.mode": "Mode",
    "quiz.mode_practice": "Practice",
    "quiz.mode_exam": "Exam",
    "quiz.timer": "Timer (minutes)",
    "quiz.no_timer": "No timer",
    "quiz.navigation": "Navigation",
    "quiz.nav_free": "Free",
    "quiz.nav_sequential": "Sequential",
    "quiz.correction": "Correction",
    "quiz.correction_instant": "Instant",
    "quiz.correction_end": "At End",
    "quiz.attempts": "Max Attempts",
    "quiz.unlimited": "Unlimited",
    "quiz.pass_mark": "Pass Mark (%)",
    "quiz.no_pass_mark": "None",
    "quiz.randomize": "Randomize order",
    "quiz.negative_marking": "Negative marking",
    "student.nav.section": "Student",
    "student.nav.dashboard": "Dashboard",
    "student.nav.courses": "Courses",
    "student.nav.quizzes": "Quizzes",
    "student.shell.clinical_journey": "Clinical Journey",
    "student.shell.semester": "Semester 1 · 2025/26",
    "student.shell.branding": "MEDlearn Student",
    "student.shell.year1": "Year 1",
    "student.shell.year1_sub": "Foundations",
    "student.shell.year2": "Year 2",
    "student.shell.year2_sub": "Pre-Clinical",
    "student.shell.year3": "Year 3",
    "student.shell.year3_sub": "Clinical",
    "student.shell.year4": "Year 4",
    "student.shell.year4_sub": "Internship",
    "student.dashboard.default_name": "Medical Student",
    "student.dashboard.semester": "Semester",
    "student.dashboard.semester_info": "Semester 1 · 2025/26",
    "student.dashboard.avg_score": "Average Score",
    "student.dashboard.overall": "Overall",
    "student.dashboard.academic_progress": "Academic Progress",
    "student.dashboard.exam_readiness": "Exam Readiness",
    "student.dashboard.retention": "Retention",
    "student.dashboard.attempt_recorded": "attempt recorded",
    "student.dashboard.attempts_recorded": "attempts recorded",
    "student.dashboard.passed": "passed",
    "student.dashboard.questions_answered": "questions answered",
    "student.dashboard.your_courses": "Your Courses",
    "student.dashboard.view_all": "View all",
    "student.dashboard.no_courses": "No courses available yet.",
    "student.dashboard.progress": "Progress",
    "student.dashboard.more": "+{count} more",
    "student.dashboard.recent_attempts": "Recent Attempts",
    "student.dashboard.quiz_fallback": "Quiz",
    "student.dashboard.no_attempts": "No attempts yet.",
    "student.dashboard.take_quiz": "Take a quiz",
    "student.dashboard.resource_hub": "Resource Hub",
    "student.dashboard.no_resources": "No resources yet.",
    "footer.rights": "© 2026 MEDlearn. All rights reserved.",
  },
  fr: {
    "payment.pending.title": "Compte en Attente d'Activation",
    "payment.pending.subtitle": "Votre compte est en attente d'approbation par un administrateur.",
    "payment.pending.step1": "Un administrateur examine votre compte",
    "payment.pending.step2": "Une fois approuvé, vous aurez accès à tout le contenu MEDlearn",
    "payment.pending.step3": "Actualisez cette page ou déconnectez-vous pour voir le changement",
    "payment.activated": "Compte Actif",
    "payment.activated_msg": "Votre compte est actif. Vous avez un accès complet au contenu MEDlearn.",
    "nav.home": "Accueil",
    "nav.majors": "Filières",
    "nav.modules": "Modules",
    "nav.resources": "Ressources",
    "nav.quizzes": "Quiz",
    "nav.admin": "Admin",
    "nav.login": "Connexion",
    "nav.signup": "S'inscrire",
    "nav.logout": "Déconnexion",
    "home.title": "MEDlearn",
    "home.subtitle": "Plateforme éducative en libre accès pour les étudiants en médecine",
    "home.badge": "Accès libre · Gratuit",
    "home.learnmore": "Parcourir les modules",
    "home.stat.modules": "Modules",
    "home.stat.resources": "Ressources",
    "home.programs_label": "Programmes académiques",
    "home.viewall": "Voir tout",
    "home.explore_major": "Explorer la filière",
    "home.community": "Fait pour la communauté des étudiants en médecine",
    "home.cta_title": "Commencez à apprendre",
    "home.cta_sub": "Aucun compte requis. Ouvrez et apprenez.",
    "home.explore": "Explorer les filières",
    "home.featured": "Programmes académiques",
    "home.empty_title": "Aucune Filière pour le Moment",
    "home.empty_desc": "Les programmes académiques sont en cours de préparation. Revenez bientôt ou explorez les modules disponibles.",
    "home.empty_cta": "Explorer les Modules",
    "majors.title": "Filières académiques",
    "majors.modules": "modules",
    "majors.available": "{count} filière disponible",
    "majors.available_plural": "{count} filières disponibles",
    "majors.search": "Rechercher des filières...",
    "majors.empty_title": "Aucune Filière Trouvée",
    "majors.empty_desc": "Aucune filière académique n'est répertoriée. Créez-en une pour commencer.",
    "majors.empty_search": "Aucune filière ne correspond à votre recherche. Essayez d'autres mots-clés.",
    "majors.empty_cta": "Créer une Filière",
    "modules.title": "Modules",
    "modules.resources": "ressources",
    "modules.single": "module",
    "modules.search": "Rechercher des modules...",
    "modules.open": "Ouvrir le module",
    "header.light_mode": "Mode Clair",
    "header.dark_mode": "Mode Sombre",
    "header.language": "Langue",
    "header.toggle_theme": "Passer en mode {mode}",
    "header.toggle_menu": "Ouvrir le menu de navigation",
    "resources.title": "Ressources",
    "resources.search": "Rechercher des ressources...",
    "resources.filter_type": "Filtrer par type",
    "resources.all": "Tout",
    "resources.file": "Fichier",
    "resources.link": "Lien",
    "resources.youtube": "YouTube",
    "resources.text": "Texte",
    "resources.empty": "Aucune ressource trouvée",
    "resources.download": "Télécharger",
    "resources.open_link": "Ouvrir le lien",
    "admin.title": "Tableau de bord",
    "admin.majors": "Filières",
    "admin.modules": "Modules",
    "admin.resources": "Ressources",
    "admin.add": "Ajouter",
    "admin.edit": "Modifier",
    "admin.delete": "Supprimer",
    "admin.save": "Enregistrer",
    "admin.cancel": "Annuler",
    "admin.name": "Nom",
    "admin.order": "Ordre",
    "admin.major": "Filière",
    "admin.module": "Module",
    "admin.type": "Type",
    "admin.title_field": "Titre",
    "admin.description": "Description",
    "admin.published": "Publié",
    "admin.language": "Langue",
    "admin.content": "Contenu",
    "admin.file": "Fichier",
    "admin.link": "URL du lien",
    "admin.youtube_id": "ID ou lien YouTube (Vidéo / Playlist)",
    "login.title": "Connexion",
    "login.email": "Email",
    "login.password": "Mot de passe",
    "login.submit": "Se connecter",
    "login.error": "Identifiants invalides",
    "empty.majors":
      "Aucune filière académique n’est encore publiée. Revenez plus tard ou contactez l’administration.",
    "empty.modules":
      "Cette filière ne comporte pas encore de modules. Le contenu est peut‑être en préparation.",
    "empty.resources":
      "Aucune ressource d’apprentissage n’est publiée pour ce module.",
    "empty.search_results":
      "Aucune ressource ne correspond à votre recherche ou à vos filtres.",
    "empty.admin.majors": "Aucune filière. Ajoutez une filière pour structurer le catalogue.",
    "empty.admin.modules": "Aucun module. Créez un module rattaché à une filière.",
    "empty.admin.resources":
      "Aucune ressource. Ajoutez des fichiers, liens, vidéos ou textes pour les étudiants.",
    "validation.major_name": "Indiquez un nom de filière.",
    "validation.module_name": "Indiquez un nom de module.",
    "validation.resource_title": "Indiquez un titre de ressource.",
    "validation.major_module": "Choisissez une filière et un module qui lui appartient.",
    "validation.language": "Utilisez un code court : en ou fr.",
    "validation.file_pick": "Choisissez un fichier à téléverser.",
    "validation.file_url": "Une URL de fichier est requise pour cette ressource.",
    "validation.url": "Saisissez une URL valide commençant par http:// ou https://.",
    "validation.youtube": "Saisissez un ID ou lien YouTube (vidéo/playlist) valide.",
    "validation.text": "Saisissez le contenu texte de la ressource.",
    "validation.resource_type": "Type de ressource non pris en charge.",
    "admin.subtitle":
      "Gérez filières, modules et ressources. Les utilisateurs connectés peuvent modifier le catalogue.",
    "admin.helper.order": "Les nombres plus petits apparaissent en premier sur le site public.",
    "admin.helper.reorder": "Déplacez vers le haut ou le bas pour modifier l’ordre d’affichage.",
    "admin.helper.select_major": "Choisissez d’abord une filière, puis ajoutez modules et ressources.",
    "admin.file.choose": "Choisir un fichier",
    "admin.file.hint":
      "Aucun fichier sélectionné. Les fichiers sont enregistrés dans le bucket Supabase « resources ».",
    "admin.file.selected": "Fichier sélectionné",
    "admin.file.replace": "Remplacer le fichier",
    "admin.file.uploading": "Téléversement…",
    "admin.file.success": "Fichier téléversé avec succès.",
    "admin.file.fail": "Échec du téléversement. Réessayez.",
    "admin.file.current": "URL du fichier actuel",
    "admin.delete.prompt": "Vous allez supprimer :",
    "admin.delete.cannot_undo": "Cette action est irréversible.",
    "admin.delete.confirm_btn": "Confirmer la suppression",
    "admin.loading": "Chargement du catalogue…",
    "admin.nav.section": "Gestion",
    "admin.nav.dashboard": "Tableau de bord",
    "admin.nav.catalog": "Filières & Modules",
    "admin.nav.resources": "Ressources",
    "admin.nav.questions": "Banque de questions",
    "admin.nav.quizzes": "Créateur de quiz",
    "admin.nav.users": "Utilisateurs",
    "admin.branding": "Admin MEDlearn",
    "admin.quicklinks": "Liens rapides",
    "admin.quiz.title": "Titre",
    "admin.quiz.title_placeholder": "Ex. Quiz sur le système cardiovasculaire",
    "admin.description_placeholder": "Description facultative du quiz…",
    "admin.quiz.select_major_hint": "Sélectionnez d'abord une filière",
    "admin.quiz.available": "Questions Disponibles",
    "admin.quiz.search_questions": "Rechercher des questions…",
    "admin.quiz.no_questions_match": "Aucune question publiée ne correspond à la filière/module sélectionné.",
    "admin.quiz.selected": "Questions Sélectionnées",
    "admin.quiz.no_questions_selected": "Aucune question ajoutée pour le moment.",
    "admin.quiz.empty": "Aucun quiz pour le moment.",
    "admin.quiz.create": "Créer un Quiz",
    "admin.quiz.draft": "Brouillon",
    "admin.questions.count": "questions",
    "admin.questions.new": "Nouvelle question",
    "admin.questions.edit": "Modifier la question",
    "admin.questions.empty": "Aucune question. Créez-en une pour alimenter la banque.",
    "admin.questions.type": "Type de question",
    "admin.questions.statement": "Énoncé",
    "admin.questions.statement_placeholder": "Rédigez l'énoncé de la question...",
    "admin.questions.explanation_placeholder": "Expliquez la réponse correcte...",
    "admin.questions.options": "Options de réponse",
    "admin.questions.correct": "Bonne réponse",
    "admin.questions.add_option": "Ajouter une option",
    "admin.questions.difficulty": "Difficulté",
    "admin.questions.explanation": "Explication",
    "admin.questions.tags": "Étiquettes",
    "admin.questions.tags_hint": "Appuyez sur Entrée ou virgule pour ajouter",
    "admin.questions.scq_hint": "Cliquez sur une lettre pour marquer la bonne réponse",
    "admin.questions.mcq_hint": "Cliquez sur les lettres pour marquer toutes les bonnes réponses",
    "admin.questions.mark_correct": "Marquer comme correct",
    "admin.questions.difficulty_none": "Aucune",
    "admin.questions.all_majors": "Toutes les filières",
    "admin.questions.all_modules": "Tous les modules",
    "admin.questions.all_types": "Tous les types",
    "admin.questions.search": "Rechercher un énoncé…",
    "quiz.untitled": "Quiz sans titre",
    "quiz.exam_mode": "Examen",
    "quiz.practice_mode": "Entraînement",
    "quiz.start_cta": "Cliquer pour commencer →",
    "quiz.no_questions": "Ce quiz n'a pas encore de questions.",
    "quiz.back": "Retour aux quiz",
    "quiz.retry": "Réessayer",
    "quiz.results": "Résultats",
    "quiz.correct": "correct(s)",
    "quiz.pass": "Réussi",
    "quiz.fail": "Échoué",
    "quiz.required": "requis",
    "quiz.review": "Révision",
    "quiz.explanation": "Explication",
    "quiz.question": "Question",
    "quiz.prev": "Précédent",
    "quiz.next": "Suivant",
    "quiz.submit": "Soumettre",
    "quiz.grading": "Correction…",
    "quiz.see_results": "Voir les résultats",
    "quiz.true": "Vrai",
    "quiz.false": "Faux",
    "empty.quizzes": "Aucun quiz publié pour ce module.",
    "quiz.plural": "Quizs",
    "quiz.new": "Nouveau Quiz",
    "quiz.edit": "Modifier le Quiz",
    "quiz.rules": "Règles du Quiz",
    "quiz.mode": "Mode",
    "quiz.mode_practice": "Entraînement",
    "quiz.mode_exam": "Examen",
    "quiz.timer": "Minuteur (minutes)",
    "quiz.no_timer": "Pas de minuteur",
    "quiz.navigation": "Navigation",
    "quiz.nav_free": "Libre",
    "quiz.nav_sequential": "Séquentielle",
    "quiz.correction": "Correction",
    "quiz.correction_instant": "Instantanée",
    "quiz.correction_end": "À la fin",
    "quiz.attempts": "Tentatives Max",
    "quiz.unlimited": "Illimité",
    "quiz.pass_mark": "Note de passage (%)",
    "quiz.no_pass_mark": "Aucune",
    "quiz.randomize": "Ordre aléatoire",
    "quiz.negative_marking": "Pénalité pour erreur",
    "student.nav.section": "Étudiant",
    "student.nav.dashboard": "Tableau de bord",
    "student.nav.courses": "Cours",
    "student.nav.quizzes": "Quiz",
    "student.shell.clinical_journey": "Parcours Clinique",
    "student.shell.semester": "Semestre 1 · 2025/26",
    "student.shell.branding": "Étudiant MEDlearn",
    "student.shell.year1": "1ère Année",
    "student.shell.year1_sub": "Fondamentaux",
    "student.shell.year2": "2ème Année",
    "student.shell.year2_sub": "Pré-Clinique",
    "student.shell.year3": "3ème Année",
    "student.shell.year3_sub": "Clinique",
    "student.shell.year4": "4ème Année",
    "student.shell.year4_sub": "Stage",
    "student.dashboard.default_name": "Étudiant en Médecine",
    "student.dashboard.semester": "Semestre",
    "student.dashboard.semester_info": "Semestre 1 · 2025/26",
    "student.dashboard.avg_score": "Score Moyen",
    "student.dashboard.overall": "Général",
    "student.dashboard.academic_progress": "Progrès Académique",
    "student.dashboard.exam_readiness": "Préparation aux Examens",
    "student.dashboard.retention": "Rétention",
    "student.dashboard.attempt_recorded": "tentative enregistrée",
    "student.dashboard.attempts_recorded": "tentatives enregistrées",
    "student.dashboard.passed": "réussi",
    "student.dashboard.questions_answered": "questions répondues",
    "student.dashboard.your_courses": "Vos Cours",
    "student.dashboard.view_all": "Voir tout",
    "student.dashboard.no_courses": "Aucun cours disponible pour le moment.",
    "student.dashboard.progress": "Progrès",
    "student.dashboard.more": "+{count} de plus",
    "student.dashboard.recent_attempts": "Tentatives Récentes",
    "student.dashboard.quiz_fallback": "Quiz",
    "student.dashboard.no_attempts": "Aucune tentative pour le moment.",
    "student.dashboard.take_quiz": "Passer un quiz",
    "student.dashboard.resource_hub": "Centre de Ressources",
    "student.dashboard.no_resources": "Aucune ressource pour le moment.",
    "footer.rights": "© 2026 MEDlearn. Tous droits réservés.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = window.localStorage.getItem(STORAGE_KEY);
    if ((saved === "en" || saved === "fr") && saved !== language) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      window.localStorage.setItem(STORAGE_KEY, lang);
    }
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = useCallback(
    (key: string) => translations[language][key] ?? key,
    [language],
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
